# Generated by Django 5.2.4 on 2025-07-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('pickup_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('weight_lbs', models.IntegerField()),
                ('distance_miles', models.IntegerField()),
                ('rate_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_type', models.CharField(max_length=50)),
                ('broker', models.CharField(max_length=100)),
            ],
        ),
    ]
